### ISSUE TITLE
Round 2 - Style

### ISSUE THREAD

**Issue by mlimberg** [StephanieEA/savery#11]
Looks like a mix of ES5 and ES6 between these two chunks of code. Would recommend picking one and being consistent all the way through. So either change line 20 to ES5 or switch line 24 to a const/arrow function.

https://github.com/StephanieEA/savery/blob/master/main.js#L20-L33

**Comment by gprocell927** [comment]
Fixed it! 🔨 🔧 :men_wrestling:
